### ISSUE TITLE
Events should have a time

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/metadatastore#14]
Each event needs to have a time associated with it

**Comment by ghost** [comment]
Rather than each individual event having a timestamp, data within an event will have the timestamp. i.e.
Event(header_id=123, seq_no=0, description='sample data with timestamp', data={'motor_val': 12.4, 'motor_ioc_time': datetime.datetime(2014, 1, 3, 18, 00, 1345)})
This is due to the fact that acquisition time from the hardware is NOT identical to database save time. As in any control system, we use time to glue multiple systems together. We have to ensure the channel archiver timestamp is identical to metadataStore timestamp for a given a PV.
