### ISSUE TITLE
API into the channel archiver

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/metadatastore#24]
I realize that this issue is really more related to the channel archiver, but I'm leaving it here as a placeholder for now.

I can see both of these as valid options for the api into the channel archiver.

Option 1:

```
def get_pv(time_list, pv_name, beamline_id, interpolation_type):
    '''
    Parameters
    ----------
    time_list: list
        list of times to obtain the values of the pv for
    pv_name: string
        pv name that the channel archiver knows about
    beamline_id: string
        Not sure if this is needed, since the channel archivers are specific to the 
        beamline (i think?)
    interpolation_type: string
        Type of interpolation to use: easy examples are linear and step function

    Returns
    -------
    list
        List of pv values interpolated based on "interpolation_type" at times 
        occurring at the values in "time_list"
   '''
```

Option 2:

```
def get_pv(t_start, t_finish, pv_name, beamline_id):
    '''
    Parameters
    ----------
    t_start : datetime.datetime
        earliest time to obtain the values of pv_name
    t_finish : datetime.datetime
        latest time to obtain the values of pv_name
    pv_name : string
        pv name that the channel archiver knows about
    beamline_id : string
        Not sure if this is needed, since the channel archivers are specific to the beamline (i think?)

    Returns
    -------
    pv_vals, time
    pv_vals : list
        List of all pv values
    time : list of datetime objects
        time stamps of pv values 
   '''
```

Thoughts @arkilic @tacaswell ?

**Comment by ghost** [comment]
We should start a dataBroker repo and start putting these together under that title so others can distinguish between metadataStore and dataBroker. 

This is great work. I think we can even facilitate channel finder to improve functionality.
http://sourceforge.net/projects/channelfinder/
ChannelFinder is snippy because IOCs can populate the database and PVs can be grouped based on several attiributes including things like beamline_id

Here is an archiver api from Australian light source. There was an issue with regular expression handling due  to differences between us and the Aussies but we've fixed them and it is ready for a ride if you'd like to try it:

Original Version:
https://github.com/RobbieClarken/channelarchiver

Our version with fixed regex:
https://github.com/eschuhmacher/channelarchiver

PS: You have an archiver running xf23id-ca if I am not mistaken. You guys can beat our version of legacy archiver's api and tell me if it is fast enough for you. SLAC archiver is much faster but lacks the api support as I am wrapping Michael Davidsaver's api which is also currently under development.
